language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
- mysql -u root -e 'CREATE DATABASE awt;'
- mysql -u root -e "CREATE USER 'awt'@'localhost' IDENTIFIED BY 'awt';"
- mysql -u root -e "GRANT ALL ON awt.* TO 'awt'@'localhost';"

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
